nameOverride: est

persistence:
  hostPath:
    enabled: true

common:
  coordinator:
    image:
      pullPolicy: Always
    resources:
      requests:
        cpu: 25m
        memory: 50Mi
  metrics-exporter:
    resources:
      requests:
        cpu: 25m
        memory: 50Mi

geth:
  image:
    repository: ethereum/client-go
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi

nethermind:
  image:
    repository: nethermindeth/nethermind
    tag: sync_test
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi

besu:
  image:
    repository: hyperledger/besu
    tag: develop
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi


lighthouse:
  image:
    repository: sigp/lighthouse
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi

prysm:
  image:
    repository: samcm/prysm-debian # Official prysm image doesnt have `sh` which is required for p2pnodeport
    # repository: gcr.io/prysmaticlabs/prysm/beacon-chain
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi

teku:
  image:
    repository: consensys/teku
    tag: develop
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi

nimbus:
  image:
    repository: statusim/nimbus-eth2
    tag: amd64-latest
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi

lodestar:
  image:
    repository: chainsafe/lodestar
    tag: next
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi

erigon:
  image:
    repository: thorax/erigon
    tag: latest
    pullPolicy: Always
  resources:
    requests:
      memory: 6000Mi
    limits:
      memory: 9000Mi

cronjob:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  activeDeadlineSeconds: 86400
  job:
    backoffLimit: 50
    restartPolicy: OnFailure
    ttlSecondsAfterFinished: 600
    terminationGracePeriodSeconds: 30
