nameOverride: est

persistence:
  hostPath:
    enabled: true

common:
  coordinator:
    image:
      pullPolicy: Always

nethermind:
  image:
    repository: nethermindeth/nethermind
    tag: sync_test
    pullPolicy: Always

nimbus:
  image:
    repository: statusim/nimbus-eth2
    tag: multiarch-v22.5.1
    pullPolicy: Always

cronjob:
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  activeDeadlineSeconds: 86400
  job:
    backoffLimit: 1
    restartPolicy: OnFailure
    ttlSecondsAfterFinished: 600
    terminationGracePeriodSeconds: 30
