geth:
  image:
    repository: ethpandaops/geth
    tag: master
    pullPolicy: Always

nethermind:
  image:
    repository: nethermindeth/nethermind
    tag: withdrawals
    pullPolicy: Always

besu:
  image:
    repository: hyperledger/besu
    tag: develop
    pullPolicy: Always


lighthouse:
  image:
    repository: sigp/lighthouse
    tag: capella
    pullPolicy: Always

prysm:
  image:
    repository: ethpandaops/prysm # Official prysm image doesnt have `sh` which is required for p2pnodeport
    # repository: gcr.io/prysmaticlabs/prysm
    tag: develop
    pullPolicy: Always

teku:
  image:
    repository: consensys/teku
    tag: develop
    pullPolicy: Always

nimbus:
  image:
    repository: ethpandaops/nimbus
    tag: unstable
    pullPolicy: Always

lodestar:
  image:
    repository: chainsafe/lodestar
    tag: next
    pullPolicy: Always

erigon:
  image:
    repository: thorax/erigon
    tag: devel
    pullPolicy: Always