name: Deploy Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deployment:
    strategy:
      matrix:
        consensus: [teku, prysm, lighthouse, nimbus]
        execution: [geth, besu, nethermind]
        network: [ropsten, kiln]
        test: [basic, complex1, complex2, complex3]
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - name: getports
        run: |
          EXECUTION_P2P_PORT=$(cat p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".execution');
          CONSENSUS_P2P_PORT=$(cat p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".consensus');

      - name: Deploy
        uses: deliverybot/helm@v1
        with:
          namespace: default
          repo: https://samcm.github.io/ethereum-sync-test-helm-chart
          chart: ethereum-sync-tests
          values: |
            global.ethereum.consensus.config.ports.p2p_tcp: ${{ env.CONSENSUS_P2P_PORT }}
            global.ethereum.consensus.config.ports.p2p_udp: ${{ env.CONSENSUS_P2P_PORT }}
            global.ethereum.execution.config.ports.p2p_tcp: ${{ env.EXECUTION_P2P_PORT }}
            global.ethereum.execution.config.ports.p2p_udp: ${{ env.EXECUTION_P2P_PORT }}

          value-files: |
            [ 
              ./deploy/values/values.yaml,
              https://raw.githubusercontent.com/samcm/ethereum-sync-test-helm-chart/main/charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml,
              https://raw.githubusercontent.com/samcm/ethereum-sync-test-helm-chart/main/charts/ethereum-sync-test/values/tests/${{ matrix.test }}.yaml"
            ]

        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}