name: Deploy Kubernetes
on:
  push:
    branches:
      - main
jobs:
  deployment:
    strategy:
      matrix:
        # consensus: [teku, prysm, lighthouse, nimbus]
        # execution: [geth, besu, nethermind]
        # network: [ropsten, kiln]
        # test: [basic, complex1, complex2, complex3]
        consensus: [teku]
        execution: [geth]
        network: [ropsten]
        test: [basic]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: getports
        run: |
          export EXECUTION_P2P_PORT=$(cat ./deploy/p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".execution');
          export CONSENSUS_P2P_PORT=;
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Add helm repo
        run: |
          helm repo add est https://samcm.github.io/ethereum-sync-test-helm-chart
      - name: Deploy
        run: |
          helm upgrade --install --timeout 2m ${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}-est est/ethereum-sync-tests \
            -f ./deploy/values/values.yaml \
            -f https://raw.githubusercontent.com/samcm/ethereum-sync-test-helm-chart/main/charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml \
            -f https://raw.githubusercontent.com/samcm/ethereum-sync-test-helm-chart/main/charts/ethereum-sync-test/values/tests/${{ matrix.test }}.yaml \
            --set global.ethereum.consensus.config.ports.p2p_tcp=$(cat ./deploy/p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".consensus') \
            --set global.ethereum.consensus.config.ports.p2p_udp=$(cat ./deploy/p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".consensus') \
            --set global.ethereum.execution.config.ports.p2p_tcp=$(cat ./deploy/p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".execution') \
            --set global.ethereum.execution.config.ports.p2p_udp=$(cat ./deploy/p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".execution') \
            --set fullnameOverride="${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}-est"
