# .github/workflows/deploy.yml
name: Deploy Kubernetes
on:
  push:
    branches:
      - main

jobs:
  deployment:
    strategy:
      matrix:
        consensus: [teku, prysm, lighthouse, nimbus]
        execution: [geth, besu, nethermind]
        network: [ropsten, kiln]
        test: [basic, complex1, complex2, complex3]
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: getports
      runs-on: ubuntu-latest
      outputs:
        execution: ${{ steps.execution.outputs.execution }}
        consensus: ${{ steps.consensus.outputs.consensus }}
      steps:
      - id: execution
        run: ::set-output name=execution::$(cat p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".execution')
      - id: consensus
        run: ::set-output name=consensus::$(cat p2p-node-ports.json | jq '."${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}".consensus')

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      needs: getports
      with:
        release: ${{ matrix.network }}-${{ matrix.consensus }}-${{ matrix.execution }}-${{ matrix.test }}
        namespace: default
        repo: https://samcm.github.io/ethereum-sync-test-helm-chart
        chart: ethereum-sync-tests
        values: |
          global.ethereum.consensus.config.ports.p2p_tcp: ${{needs.getports.outputs.consensus}}
          global.ethereum.consensus.config.ports.p2p_udp: ${{needs.getports.outputs.consensus}}
          global.ethereum.execution.config.ports.p2p_tcp: ${{needs.getports.outputs.execution}}
          global.ethereum.execution.config.ports.p2p_udp: ${{needs.getports.outputs.execution}}
        value-files:
        - "./deploy/values/values.yaml",
        - "https://raw.githubusercontent.com/samcm/ethereum-sync-test-helm-chart/main/charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml",
        - "https://raw.githubusercontent.com/samcm/ethereum-sync-test-helm-chart/main/charts/ethereum-sync-test/values/tests/${{ matrix.test }}.yaml"
      
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'