name: '[Cron] Test: Is-Healthy'
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 7 * * MON'
jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        consensus: [lighthouse, teku, prysm, nimbus, lodestar]
        execution: [geth, besu, nethermind, erigon]
        network: [ropsten, kiln]
        test: [is-healthy]
        exclude:
          - network: kiln
            consensus: nimbus
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        uses: ./.github/actions/run-test-kubernetes
        with:
          ## Variables
          consensus: ${{ matrix.consensus }}
          execution: ${{ matrix.execution }}
          network: ${{ matrix.network }}
          test: ${{ matrix.test }}
          uploadDB: false
          kubernetesCluster: kind

          ## Config/secrets
          kubeConfig: ${{ secrets.KUBECONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/download-artifact@v3
        if: ${{ always() }}
        with:
          name: coordinator.log
          path: coordinator.log
      - uses: actions/download-artifact@v3
        if: ${{ always() }}
        with:
          name: metrics-exporter.log
          path: metrics-exporter.log
      - uses: actions/download-artifact@v3
        if: ${{ always() }}
        with:
          name: consensus.log
          path: consensus.log
      - uses: actions/download-artifact@v3
        if: ${{ always() }}
        with:
          name: execution.log
          path: execution.log
      - uses: actions/download-artifact@v3
        if: ${{ always() }}
        with:
          name: jobspec.yaml
          path: jobspec.yaml
      - uses: actions/download-artifact@v3
        if: ${{ always() }}
        with:
          name: links.yaml
          path: links.yaml
      - name: Print links
        shell: bash
        run: |
          cat links.txt
      - name: Print Coordinator logs
        shell: bash
        run: |
          cat coordinator.log
      - name: Print Metrics-Exporter logs
        shell: bash
        run: |
          cat metrics-exporter.log
      - name: Print Consensus logs
        shell: bash
        run: |
          cat consensus.log
      - name: Print Execution logs
        shell: bash
        run: |
          cat execution.log
      - name: Print Job Spec
        shell: bash
        run: |
          cat jobspec.yaml


