name: '[Cron] Test: Is-Healthy'
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '0 8 * * MON'
jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        consensus: [lighthouse, teku, prysm, nimbus, lodestar]
        execution: [geth, besu, nethermind, erigon]
        network: [zhejiang]
        test: [is-healthy]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        id: run-test
        uses: ./.github/actions/run-test-kubernetes
        with:
          ## Variables
          consensus: ${{ matrix.consensus }}
          execution: ${{ matrix.execution }}
          network: ${{ matrix.network }}
          test: ${{ matrix.test }}
          uploadDB: false
          kubernetesCluster: kind

          ## Config/secrets
          kubeConfig: ${{ inputs.kubernetes-engine == 'ibm' && secrets.KUBECONFIG_CLUSTERB || secrets.KUBECONFIG }}
      - name: rclone
        uses: wei/rclone@v1
        if: ${{ always() }}
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ./ spaces://ethereum-sync-tests/tests/${{ steps.run-test.outputs.job }}/
      - name: Print Job ID
        shell: bash
        if: ${{ always() }}
        run: |
          echo ${{ steps.run-test.outputs.job }}
      - name: Print links
        shell: bash
        if: ${{ always() }}
        run: |
          cat links.txt
