name: '[Cron] Test: Ropsten Complex-3'
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * THU'
jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        consensus: [lighthouse, teku, prysm, nimbus, lodestar]
        execution: [geth, besu, nethermind, erigon]
        network: [ropsten]
        test: [complex3]
    runs-on: self-hosted
    timeout-minutes: 2880
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        id: run-test
        uses: ./.github/actions/run-test-kubernetes
        with:
          ## Variables
          consensus: ${{ matrix.consensus }}
          execution: ${{ matrix.execution }}
          network: ${{ matrix.network }}
          test: ${{ matrix.test }}
          uploadDB: false
          kubernetesCluster: do

          ## Config/secrets
          kubeConfig: ${{ secrets.KUBECONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: rclone
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: copy ./ spaces://ethereum-sync-tests/tests/${{ steps.run-test.outputs.job }}/
      - name: Print links
        shell: bash
        if: ${{ always() }}
        run: |
          cat links.txt
      - name: Print Coordinator logs
        shell: bash
        if: ${{ always() }}
        run: |
          cat coordinator.log
      - name: Print Metrics-Exporter logs
        shell: bash
        if: ${{ always() }}
        run: |
          cat metrics-exporter.log
      - name: Print Consensus logs
        shell: bash
        if: ${{ always() }}
        run: |
          cat consensus.log
      - name: Print Execution logs
        shell: bash
        if: ${{ always() }}
        run: |
          cat execution.log
      - name: Print Job Spec
        if: ${{ always() }}
        shell: bash
        run: |
          cat jobspec.yaml