name: Run test on Kubernetes
on:
  push:
    branches:
      - main
jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        consensus: [lighthouse]
        execution: [geth]
        network: [ropsten]
        test: [starts-syncing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create kube config
        run: |
          mkdir -p $HOME/.kube/
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Install helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
      - name: Add helm repo
        run: |
          helm repo add est https://samcm.github.io/ethereum-sync-test-helm-chart
      - name: Deploy
        run: |
          helm upgrade --install --version 0.57.0 --namespace=ethereum --timeout 2m ${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}-est-gh est/ethereum-sync-tests \
            -f ./deploy/values/values.yaml \
            -f https://raw.githubusercontent.com/samcm/ethereum-sync-test-helm-chart/main/charts/ethereum-sync-test/values/networks/${{ matrix.network }}.yaml \
            -f https://raw.githubusercontent.com/samcm/ethereum-sync-test-helm-chart/main/charts/ethereum-sync-test/values/tests/${{ matrix.test }}.yaml \
            --set global.ethereum.consensus.config.ports.p2p_tcp=30241 \
            --set global.ethereum.consensus.config.ports.p2p_udp=30241 \
            --set global.ethereum.execution.config.ports.p2p_tcp=30242 \
            --set global.ethereum.execution.config.ports.p2p_udp=30242 \
            --set cronjob.suspend=true \
            --set fullnameOverride="${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}-est-gh"
      - name: Install stern
        run: >
          curl https://github.com/stern/stern/releases/download/v1.21.0/stern_1.21.0_linux_amd64.tar.gz -L -o stern.tar.gz;
          tar -xvf stern.tar.gz;
          ls -al;
          chmod +x stern;
          ./stern --version;
      - name: Run test
        run: |
          job=$(echo ${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}-est-gh-$(date +%s));
          kubectl create job $job -n ethereum --from cronjob/${{ matrix.network }}-${{ matrix.test }}-${{ matrix.consensus }}-${{ matrix.execution }}-est-gh;
          echo "Job $job created";
          ./stern -n ethereum $job -c coordinator > coordinator.log &
          ./stern -n ethereum $job -c metrics-exporter > metrics-exporter.log &
          ./stern -n ethereum $job -c consensus > consensus.log &
          ./stern -n ethereum $job -c execution > execution.log &
          echo "Log watchers created";
          kubectl -n ethereum wait --timeout=-1s --for=condition=complete job/$job;
          echo "Job $job completed";
      - uses: actions/upload-artifact@v3
        with:
          name: coordinator.log
          path: coordinator.log
      - uses: actions/upload-artifact@v3
        with:
          name: metrics-exporter.log
          path: metrics-exporter.log
      - uses: actions/upload-artifact@v3
        with:
          name: consensus.log
          path: consensus.log
      - uses: actions/upload-artifact@v3
        with:
          name: execution.log
          path: execution.log



