name: '[Cron] Test: Starts-Syncing'
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 7 * * MON'
jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        consensus: [lighthouse, teku, prysm, nimbus, lodestar]
        execution: [geth, besu, nethermind, erigon]
        network: [ropsten, kiln]
        test: [starts-syncing]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        uses: ./.github/actions/run-test-kubernetes
        with:
          ## Variables
          consensus: ${{ matrix.consensus }}
          execution: ${{ matrix.execution }}
          network: ${{ matrix.network }}
          test: ${{ matrix.test }}
          uploadDB: false
          kubernetesCluster: kind

          ## Config/secrets
          kubeConfig: ${{ secrets.KUBECONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Print links
        shell: bash
        if: ${{ always() }}
        run: |
          cat links.txt
      - name: Print Coordinator logs
        shell: bash
        if: ${{ always() }}
        run: |
          cat coordinator.log
      - name: Print Metrics-Exporter logs
        shell: bash
        if: ${{ always() }}
        run: |
          cat metrics-exporter.log
      - name: Print Consensus logs
        shell: bash
        if: ${{ always() }}
        run: |
          cat consensus.log
      - name: Print Execution logs
        shell: bash
        if: ${{ always() }}
        run: |
          cat execution.log
      - name: Print Job Spec
        if: ${{ always() }}
        shell: bash
        run: |
          cat jobspec.yaml