name: Run to-head test on Kubernetes
on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 8 * * MON'
jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        consensus: [lighthouse, teku, prysm, nimbus, lodestar]
        execution: [geth, besu, nethermind]
        network: [ropsten, kiln]
        test: [starts-syncing]
    runs-on: self-hosted
    timeout-minutes: 1440
    steps:
      - uses: actions/checkout@v1
      - name: Run test
        uses: ./.github/actions/run-test-kubernetes
        with:
          ## Variables
          consensus: ${{ matrix.consensus }}
          execution: ${{ matrix.execution }}
          network: ${{ matrix.network }}
          test: ${{ matrix.test }}
          uploadDB: false

          ## Config/secrets
          kubeConfig: ${{ secrets.KUBECONFIG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
